version: 2

project_name: tz
release:
  github:
    owner: demarsdouglas
    name: tz-cli

builds:
  - id: tz
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/demarsdouglas/tz-cli/cmd.version={{.Version}}

archives:
  - formats: [ 'tar.gz' ]
    name_template: "tz-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc

homebrew_casks:
  - name: tz
    binary: tz
    description: "Realtime timezone viewer CLI"
    homepage: "https://github.com/demarsdouglas/tz-cli"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    directory: Casks
    url:
      template: "https://github.com/demarsdouglas/tz-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
      verified: "github.com/demarsdouglas/tz-cli"


