version: 2

project_name: tz
release:
  github:
    owner: demarsdouglas
    name: tz-cli

builds:
  - id: tz
    main: ./main.go
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/demarsdouglas/tz-cli/cmd.version={{.Version}}

archives:
  - format: tar.gz
    name_template: "tz-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: desc

brews:
  - name: tz
    description: "Realtime timezone viewer CLI"
    homepage: "https://github.com/demarsdouglas/tz-cli"
    repository:
      owner: demarsdouglas
      name: homebrew-tap
      branch: main
      directory: Formula
    commit_author:
      name: GoReleaser Bot
      email: bot@goreleaser.com
    install: |
      bin.install "tz"

